### ISSUE TITLE
Question - Optional Fields

### ISSUE THREAD

**Issue by damianoneill** [jszwec/csvutil#14]
Hi Jacek, I was wondering if it's possible to Unmarshal the following type of struct(s) using csvutil? 

```go
type Device struct {
	DeviceID       string          `json:"device-id" yaml:"device-id"`
	Host           string          `json:"host"`
	SystemID       string          `json:"system-id,omitempty" yaml:"system-id,omitempty"`
	Authentication *Authentication `json:"authentication,omitempty" yaml:"authentication,omitempty"`
	IAgent         *IAgent         `json:"iAgent,omitempty" yaml:"iAgent,omitempty"`
	OpenConfig     *OpenConfig     `json:"open-config,omitempty" yaml:"open-config,omitempty"`
	Snmp           *Snmp           `json:"snmp,omitempty" yaml:"snmp,omitempty"`
	Vendor         *Vendor         `json:"vendor,omitempty" yaml:"vendor,omitempty"`
}
```

Where I'm using pointers to indicate optional content when unmarshaling from a variety of file types. 

Thanks in advance,
Damian.

**Comment by jszwec** [comment]
Hello Damian,

Yes it is possibile, but it really depends on what the CSV representation of your struct looks like.
Based on what I see `Authentication`, `IAgent`, `OpenConfig`, `Snmp` and `Vendor` would need to be all single columns in one row. I don't know how you would like to represent them as a single column. When you decide, you will need to implement `MarshalCSV` and `UnmarshalCSV` methods for each type.

**Comment by damianoneill** [comment]
Thanks Jacek for the quick response.  The api design is driven by a third party. The full type looks like. 

```go
// Devices - collection of Device
type Devices struct {
	Device []Device `json:"device"`
}

// Password - wrapper for uname/password
type Password struct {
	Password *string `json:"password"`
	Username *string `json:"username"`
}

// Authentication - Collection type for Auth options
type Authentication struct {
	Password Password `json:"password,omitempty" yaml:"password,omitempty"`
}

// IAgent - configure the NETCONF port
type IAgent struct {
	Port int `json:"port"`
}

// OpenConfig - configure the Open Config port
type OpenConfig struct {
	Port int `json:"port"`
}

// V2 - configure the SNMP community string
type V2 struct {
	Community string `json:"community"`
}

// Snmp - configure the SNMP port or Community String
type Snmp struct {
	Port int `json:"port,omitempty" yaml:"port,omitempty"`
	V2   *V2 `json:"v2,omitempty" yaml:"v2,omitempty"`
}

// Juniper - option to define the Operating system
type Juniper struct {
	OperatingSystem string `json:"operating-system" yaml:"operating-system"`
}

// Cisco - option to define the Operating system
type Cisco struct {
	OperatingSystem string `json:"operating-system" yaml:"operating-system"`
}

// Vendor - Configure the Vendor information
type Vendor struct {
	Juniper *Juniper `json:"juniper,omitempty" yaml:"juniper,omitempty"`
	Cisco   *Cisco   `json:"cisco,omitempty" yaml:"cisco,omitempty"`
}

// Device - info needed to Register a Device in Healthbot
type Device struct {
	DeviceID       string          `json:"device-id" yaml:"device-id"`
	Host           string          `json:"host"`
	SystemID       string          `json:"system-id,omitempty" yaml:"system-id,omitempty"`
	Authentication *Authentication `json:"authentication,omitempty" yaml:"authentication,omitempty"`
	IAgent         *IAgent         `json:"iAgent,omitempty" yaml:"iAgent,omitempty"`
	OpenConfig     *OpenConfig     `json:"open-config,omitempty" yaml:"open-config,omitempty"`
	Snmp           *Snmp           `json:"snmp,omitempty" yaml:"snmp,omitempty"`
	Vendor         *Vendor         `json:"vendor,omitempty" yaml:"vendor,omitempty"`
}
```

Are you suggesting for each nested pointer struct I need to implement custom marshal / unmarshal?

**Comment by jszwec** [comment]
What CSV representation of `Device` is supposed to look like?

**Comment by damianoneill** [comment]
I can drive the input, the official input format is yaml based, json for output, I’d like to offer csv as an alternative input option, I can mandate what the format will be.  

The reason for raising the original question is that I tried the following; 

```go
var fakeDevices = Devices{
   Device: []Device{{
      DeviceID: "test-device",
      Host:     "10.0.0.1",
   }},
}


func TestMarshalCsv(t *testing.T) {
   b, err := csvutil.Marshal(fakeDevices.Device)
   t.Log(err, b)
}
```

Got a 

```go
csvutil: unsupported type: dsl.Authentication []
```
So just wanted to confirm pointer struct support before investigating.

**Comment by jszwec** [comment]
CSV values are arrays by themselves. Struct in CSV represents a row where fields are columns.
In your example, you are trying to encode a single row that has a column which represents a slice of devices - that's why you got an error. I think you want to be encoding `[]Device` values.

Pointers are supported for any type. Structs must implement `csvutil.Marshaler` and/or `csvutil.Unmarshaler` unless they are embedded and have no tag like [here](https://github.com/jszwec/csvutil#examples_nested_structs)

If I were you, I would first write down a sample CSV, and then I would focus on how to encode/decode it.

**Comment by damianoneill** [comment]
Thanks @jszwec appreciate you explaining.
