### ISSUE TITLE
Question - regex for delimiters?

### ISSUE THREAD

**Issue by damianoneill** [jszwec/csvutil#15]
Hi @jszwec have you ever given consideration to supporting regex as the delimiter / separator ? Rather than a string?

For e.g. "[ ]{1,}" to indicate one or more spaces as the delimiter as in 

csvReader.Comma = '[ ]{1,}'

```console
10.0.0.1   pe1   "Site a"   "Rack 1"   root   changeme
10.0.0.2   pe2   "Site a"   "Rack 2"   root   changeme
```

Thanks,
Damian.

**Comment by jszwec** [comment]
Hi Damian,

This is out of the scope of this package. Csvutil provides struct mapping, not a parser. The `Comma` field that you are referring to is part of the std [csv package](https://golang.org/pkg/encoding/csv/). However, if you have a working parser that does what you need and it implements `csvutil.Reader` and `csvutil.Writer` you can use it with csvutil.

As the README says:

> Package csvutil provides fast and idiomatic mapping between CSV and Go (golang) values.
>
>This package does not provide a CSV parser itself, it is based on the [Reader](https://godoc.org/github.com/jszwec/csvutil#Reader) and [Writer](https://godoc.org/github.com/jszwec/csvutil#Writer)
interfaces which are implemented by eg. std Go (golang) [csv package](https://golang.org/pkg/encoding/csv). This gives a possibility
of choosing any other CSV writer or reader which may be more performant.

**Comment by damianoneill** [comment]
Thanks @jszwec
