### ISSUE TITLE
Multi header support

### ISSUE THREAD

**Issue by ferhatelmas** [jszwec/csvutil#2]
```go
	var csvInput1 = []byte(`
name,age
jacek,26
john,27`,
	)

	var csvInput2 = []byte(`
description,age
jacek,26
john,27`,
	)

	type User struct {
		Name string `csv:"name|description"`
		Age  int    `csv:"age"`
	}
```

**Comment by jszwec** [comment]
I am opposed to this idea.

If for some reason the input file has header `name,description,age`, then the choice between them is ambiguous. The same goes for the Encoder, it would have to decide if Name should be encoded as "name" or "description".

There are two possible ways of handling such case

```go
type User struct {
    Name string          `csv:"name"`
    Description string   `csv:"description"`
    Age int              `csv:"age"`
}

func (u User) ID() string {
   if u.Name != "" {
       return u.Name
    }
    return u.Description
}
```

Or if you don't want Description to be part of your struct:

```go
for {
    if err := dec.Decode(&u); err == io.EOF {
        break
    } else if err != nil {
         return err
    }

    if u.Name == "" {
        for _, i := range dec.Unused() {
           if dec.Header()[i] == "description" {
               u.Name = dec.Record()[i]
           }
        }
}
```

I would recommend to go with the first one. The choice between these columns should be part of the program's logic, csvutil should only be responsible for serialization/deserialization.
