### ISSUE TITLE
Add support for inlining struct fields with tag name serving as a prefix

### ISSUE THREAD

**Issue by ptimson** [jszwec/csvutil#24]
Hello in my code I wish to name something different to the type. I've taken your example:
https://play.golang.org/p/-BMWe52rd1d

```
package main

import (
	"fmt"

	"github.com/jszwec/csvutil"
)

type Address struct {
	Street string `csv:"street"`
	City   string `csv:"city"`
}

type User struct {
	Name string `csv:"name"`
	Location Address
}

func main() {
	users := []User{
		{
			Name: "John",
			Location: Address{
				Street: "Boylston",
				City:   "Boston",
			},
		},
	}

	b, err := csvutil.Marshal(users)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%s\n", b)

	var out []User
	if err := csvutil.Unmarshal(b, &out); err != nil {
		panic(err)
	}

	fmt.Printf("%+v\n", out)
```

However I then get `panic: csvutil: unsupported type: main.Address`. 

Is there a way to support this?

I'm guessing your reasoning is that you can't have more than one `Address` as the headers would then be duplicated. But what happens if you were to prefix the struct name e.g.

```
type Address struct {
	Street string `csv:"street"`
	City   string `csv:"city"`
}

type User struct {
	Name string `csv:"name"`
        HomeAddress Address `csv:"home_address"`
        WorkAddress Address `csv:"work_address"`
}

name,home_address_street,home_address_city,work_address_street,work_address_city
```

**Comment by jszwec** [comment]
Interesting. We probably could implement it via additional tag (`inline` perhaps?) that could treat this struct field as an embedded struct and treat the tag name as the prefix. Im not yet sure if it's worth adding a complexity like that. Let me think about it.

If you are looking for a workaround you could probably do something like this:
```go
type address struct {
	Street string 
	City   string 
}

type WorkAddress struct {
	Street string   `csv:"work_street"`
	City   string   `csv:"work_city"`
}

type HomeAddress struct {
	Street string  `csv:"home_street"`
	City   string  `csv:"home_city"`
}

// ensure the types are the same
var (
  _ = Address(WorkAddress{})
  _ = Address(HomeAddress{})
)

type User struct {
	Name string `csv:"name"`
        HomeAddress
        WorkAddress 
}
```

The reason for `address` struct existince is that you can cast the Home and Work address to it so that you can pass it as a generic address: https://play.golang.org/p/Qxy0hnJqJ_b

**Comment by jszwec** [comment]
@ptimson you can now use this feature in v1.3.0

You can find the example here: https://github.com/jszwec/csvutil#examples_inlined_structs
