### ISSUE TITLE
encoder header editable

### ISSUE THREAD

**Issue by Wishlily** [jszwec/csvutil#3]
like `func NewEncoder(w Writer, header ...string) *Encoder`

For example, a file is as follows:

```
title1,title2,oldtitle,title3
data1,data2,olddata,data3
...
```

my struct:

```
type test struct {
	T1 string `csv:"title1"`
	T2 string `csv:"title2"`
	T3 string `csv:"title3"`
}
```

I want write new data like this:

```
title1,title2,oldtitle,title3
data1,data2,olddata,data3
new1,new2,,new3
```

**Comment by jszwec** [comment]
I have given it more thought and did some research. It looks like [encoding/binary](https://golang.org/pkg/encoding/binary/) uses blank fields for padding, so can we for lets call it "default headers"

My plan is to go with the following behavior:
```go
type Foo struct {
	_ int    // this is ignored due to lack of tag
	_ int    `csv:"f1"`
	_ string `csv:"f2"`
	F int    `csv:"f3"`
}
```

Encoding Foo struct{F:5} will result in
```
f1,f2,f3
0,,5
```

Values for blank fields will be default values for the given type - int 0, string "", interface{} "" etc...

I created a new branch "blank" where the code is mostly ready but still requires some work on documentation. Feel free to check it out and let me know if it solves your problem.

**Comment by Wishlily** [comment]
Thank you for your answer.
Forgive my poor English (╥﹏╥) 

This is not a normal case for me, I think if I don't know that `old_title` exists in the csv file, what should I do.
This is more like error handling or version compatibility issues.
Maybe I should throw an error or create more `struct` to handle it.

**Comment by jszwec** [comment]
I think that the idea behind the Encoder is that you are creating the file, so it is only up to you if you want this column to be there.

If you want to read the file, you can use the Decoder and easily check if the column was present or not. You could either use Decoder.Unused + Decoder.Header or create a struct

```go
type test struct {
  	T1 string `csv:"title1"`
	T2 string `csv:"title2"`
        OldTitle *string `csv:"oldtitle"`
	T3 string `csv:"title3"`
}
```

use `Decoder.Decode()` on it and if OldTitle == nil it means the column was not present
