### ISSUE TITLE
unmarshal is not compatible with utf8 bom

### ISSUE THREAD

**Issue by jxskiss** [jszwec/csvutil#32]
```
data, _ := ioutil.ReadFile("file.csv")
_ = csvutil.Unmarshal(data, &dst)
```

If file.csv has UTF8 BOM, the first column can not be parsed.

**Comment by jszwec** [comment]
csvutil is not a parser, it only provides value mapping. Default functions like Unmarshal and Marshal use csv.Writer and csv.Reader by default. You should look here: https://github.com/golang/go/issues/33887

**Comment by sergolius** [comment]
There is way how to get rid of BOM by using Go "Standard library": https://stackoverflow.com/a/76023436
Based on answer from stackoverflow, removing BOM from `[]byte` :

```go
func BOMAwareAppend(dst []byte, src []byte) (result []byte, n int, err error) {
	transformer := unicode.BOMOverride(encoding.Nop.NewDecoder())
	return transform.Append(transformer, dst, src)
}

buf, _, err := BOMAwareAppend(buf[:0], buf) // in-place to avoid allocation
```
