### ISSUE TITLE
Add validation for header 

### ISSUE THREAD

**Issue by lev112** [jszwec/csvutil#33]
in the current implementation, 
if a field is defined in the struct, but is missing from the csv,
during the decode, the field will be assigned the zero value

requested feature:
if a column is missing from the csv, the decode should return an error.
to maintain backward compatibility, can add a tag `mandatory`, and validate fields only with that tag

**Comment by jszwec** [comment]
In some cases this tag could bring some confusion. For example:
```go
Number int `csv:",omitempty,mandatory"`
```
which would mean, I require that column, but I allow an empty string.

I am hesitant to add a new tag, I would rather add a Decoder option such as:
```go
DisallowMissingColumns bool
```
It doesn't give you per field granularity, but if your struct is really big, then you don't have to type `mandatory` for each filed.

In case you care only about certain fields you can validate header yourself.
```go
dec, err := csvutil.NewDecoder(r)
if err != nil {
...
}

validateHeader(dec.Header())
```
