### ISSUE TITLE
Unmarshalling 0 and 1 into boolean field

### ISSUE THREAD

**Issue by pocockn** [jszwec/csvutil#35]
I have a struct with some bool fields. When I unmarshal my CSV the fields have 0 and 1. 

I'd expect these to get unmarshaled into 1 for true and 0 for false but they all get unmarshaled into false.

Is it possible to achieve this without having to write a custom unmarshal function for each bool?

**Comment by jszwec** [comment]
it is - decoder uses [ParseBool](https://golang.org/pkg/strconv/#ParseBool) which accepts 1 and 0. Make sure your header and tags match.
