### ISSUE TITLE
DisallowMissingColumns feature through csv tags

### ISSUE THREAD

**Issue by mariaefi29** [jszwec/csvutil#38]
Hi @jszwec,

Thank you a useful library!

We use this library extensively now, however, we feel like that it is not easy to use `DisallowMissingColumns` feature through decoder.

What do you think that we find the way to specify this requirement using tags in a struct, so we can just simply use Unmarshal straight and it will fail when of of the columns if missing?

For example:

```
type Item struct {
	ID          string `csv:"id, required"`
	Type     string `csv:"type, required"`
	Name    string `csv:"name"`
}
```

Perhaps some other name, not `required`.

It would mean that if file does't contain `id` and `type` columns, we will fail unmarshaling. 
However, if the file doesn't contain `name` column, that is totally fine, we can use default value.

**Comment by jszwec** [comment]
Hello @mariaefi29,

I'm glad to hear that you find csvutil useful! I'd like to avoid the tag for the reasons that I outlined in this issue: https://github.com/jszwec/csvutil/issues/33

Could you give me more feedback as to why using `DisallowMissingColumns` is not easy? Is it because you have to build a decoder?

**Comment by mariaefi29** [comment]
Dear @jszwec,

Oh, I see! Sorry for not reading the previous thread more closely!

Yes, your remarks make sense! Tags are not the best choice either.

I guess the inconvenience is more about building a decoder for a simple cases, not about more granular control.

Have you considered adding an option in the `Unmarshal` func? 
For instance, the func could look like that:

```
err := csvustil.Unmarshal(data, &items, csvutil.WithHeadersValidation)
```

or does it seem like an overhead to you?

**Comment by jszwec** [comment]
Hello @mariaefi29 

It's an interesting idea with Options, but I'm afraid it would break backward compatibility. Consider the following use case (actually one of my use cases)
```go
	decodeMap := map[string]func([]byte, interface{}) error{
		"json": json.Unmarshal,
		"xml":  xml.Unmarshal,
		"csv":  csvutil.Unmarshal,
	}
```
We would have to introduce a new function - I don't want to do that. I would probably be leaning towards tag option more. However, I am still not fully happy with it. I can see how it could be useful, but at the same time it feels like a validation problem. I may be wrong, but it seems that if someone validates their decoded values this feature becomes redundant.
```go
type Foo struct {
  ID string `csv:"id,required"`
}
```
Column is required, but does it make sense for the ID to be empty? In most cases probably not, so we should validate it anyway. If column is empty, ID is empty so it's invalid. If we need to distinguish between empty value and missing column we can do
```go
type Foo struct {
  ID *string `csv:"id"` // use a pointer or type similar to sql.NullString
}
```
if ID is nil, then the column is missing. Other option is to check `Decoder.Header()` before the first call to `Decoder.Decode`.

Overall `required` is a slightly different use case than DisallowMissingColumns.
At the same time, this convenience problem is true for every other Decoder option (like tag or map). JSON Decoder has similar problems. I usually solve it by wrapping it in convenience functions eg:
```go
func unmarshal(r io.Reader, v interface{}) error {
  dec, err := csvutil.NewDecoder(csv.NewReader(r))
  if err != nil {
     return err
  }
  dec.DisallowMissingColumns = true
  return dec.Decode(v) // assuming that v is a slice
}

...

var foos []Foo
err := unmarshal(r, &foos)
``` 

As of right now, I can't offer a better alternative to `required` tag, I need to explore this more.

**Comment by mariaefi29** [comment]
Dear @jszwec,

Thank you for such a good explanation!

I totally understand your concerns. There are definitely drawbacks.

I think that wrapper function works for us pretty well. Thank you! Should I close the issue then?
