### ISSUE TITLE
Question: not possible to note write an entire column if all values empty?

### ISSUE THREAD

**Issue by foob26uk** [jszwec/csvutil#40]
Hello, thanks for providing this useful csv reader/writer.

Is there a tag I can use to indicate that I don't want a column written if all its values are empty?

I tested out "omitempty" and with the tag or without, it doesn't affect anything when marshaling.

**Comment by jszwec** [comment]
Hello,
Skipping the entire column is not possible because it would require us to know (and scan) the entire data set up front.
csvutil has been designed with streaming in mind so I don't think it will ever be possible.

**Comment by foob26uk** [comment]
That makes sense thanks. What does omitempty actually do?

**Comment by jszwec** [comment]
Encoder: if value is a default value such as `""`, `0`, `false`, `nil` it is being encoded as en empty string

Decoder: if string value is empty it is being skipped from decoding

You can find more information and examples in godoc: https://pkg.go.dev/github.com/jszwec/csvutil#Encoder.Encode

**Comment by foob26uk** [comment]
Thanks man.

**Comment by jszwec** [comment]
> What is "if string value is empty it is being skipped from decoding"? Seems to already skip for me, just defaults to empty string when csv field is missing. Doesn't throw error even if I don't use omitempty.

This means that decoding the following CSV:
```
A,B
something,
```

with 

```
type struct {
  A string
  B int `csv:",omitempty"
}
```

will **not** fail: https://play.golang.org/p/cGPAW4lGt5V

It's all described in the docs: https://pkg.go.dev/github.com/jszwec/csvutil#Decoder.Decode
Under `Examples of struct field tags and their meanings:`

```
// Decode matches this field with "myName" header column and decoding is not
// called if record's field is an empty string.
Field int `csv:"myName,omitempty"`
```
