### ISSUE TITLE
feature request: "inline" array elements (similar to inline tag for structs)

### ISSUE THREAD

**Issue by mewmew** [jszwec/csvutil#46]
Hi Jacek,

First off, I would like to take my hat of and applaud the effort you've been undertaking! The capabilities of `csvutil` are really quite impressive, especially when it comes to handling custom fields/tags/marshaling requirements, etc.

Even given the extensive support for custom marshaling/unmarshaling in `csvutil`, there is still one situation I would like to explore.

Lets say we have a struct `T` containing a few fields, one of which is an array; e.g.
```go
type T1 struct {
   A int
   B string
   C [3]int `csv:"C_,inline"`
}

var data1 = T1{A: 123, B: "foo", C: [3]int{1, 2, 3}}
```

Marshaling the above above struct with `csvutil` would give the following error: `unsupported type: [3]int`.

However, a very similar situation is supported with inline struct fields, namely:
```go
type T2 struct {
   A int
   B string
   C X `csv:"C_,inline"`
}

type X struct {
   F1 int
   F2 int
   F3 int
}

var data2 = T2{A: 123, B: "foo", C: X{F1: 1, F2: 2, F3: 3}}
```

Which would marshal into:

```csv
A   , B     , C_F1 , C_F2 , C_F3
123 , "foo" , 1    , 2    , 3
```

## Feature request

If it were possible to handle array fields in a similar fashion as "inline" struct fields, inlining the respective elements of the array, assigning name prefixes analogous to how its done for inlined structs, and using array element index as name suffix.

Given the example above, `data1` would marshal into (using 1-indexed name suffixes for array element indices):

```csv
A   , B     , C_1 , C_2 , C_3
123 , "foo" , 1   , 2   , 3
```

The support for "inlined" arrays, would preferably be be implemented in a orthogonal way such that it naturally supports arrays with struct element types.

One such example would be:

```go
type T3 struct {
   A int
   B string
   C [3]Y `csv:"C_,inline"`
}

type Y struct {
   D int
   E string
}

var data3 = T3{
   A: 123,
   B: "foo",
   C: [3]Y{
      Y{D: 1, E: "bar"},
      Y{D: 2, E: "baz"},
      Y{D: 3, E: "qux"},
   },
}
```

Given the example above, `data3` would marshal into:

```csv
A   , B     , C_D1 , C_E1 , C_D2 , C_E2 , C_D3 , C_E3
123 , "foo" , 1   , "bar" , 2   , "baz" , 3   , "qux"
```

Any thoughts or ideas? I'd be happy to bounce ideas and discuss any unforeseen issues with the proposal.

Wish you happy coding and a most lovely Autumn.

Cheerful regards,
Robin

**Comment by jszwec** [comment]
Hey Robin,

Thank you for your kind words.

Your proposal makes sense to me, but Im wondering if we could achieve the same and more by extending the tag's capabilities with a `*` pattern similarly to `ioutil.TempDir`. For example:

```go
type T3 struct {
   A int
   B string
   C1 Y `csv:"C_*1,inline"`
   C2 Y `csv:"C_*2,inline"`
   C3 Y `csv:"C_*3,inline"`
}

type Y struct {
   D int
   E string
}

var data3 = T3{
   A: 123,
   B: "foo",
   C1: Y{D: 1, E: "bar"},
   C2: Y{D: 2, E: "baz"},
   C3: Y{D: 3, E: "qux"},
   },
}
```

out:
```
A   , B     , C_D1 , C_E1 , C_D2 , C_E2 , C_D3 , C_E3
123 , "foo" , 1   , "bar" , 2   , "baz" , 3   , "qux"
```

**pros:**
* no special treatment for arrays
* arrays have a fixed size so there is no difference between defining 3 fields vs 3-element array
* arrays would have a limitation of having a "digit" suffix, while with the above you can choose whatever you want
* less complexity and code for both decoder and encoder - I believe that adding `*` should be a fairly easy change while arrays would be much more work

**cons**
* `*` would not be possible in the column name when `inline` tag is used

Let me know what you think,
Jacek

**Comment by mewmew** [comment]
Hi Jacek,

Glad to hear from you.

I think your counter-proposal has value, especially as it gives the ability to add arbitrary suffixes, which may be useful in general.

I'll provide further rationale why I still think it is worth adding support for arrays, and why I think the increased complexity of the encoder/decoder may be justified.

The main reason is that it may not always be possible to change the data type representation to use a set of fields (essentially an "unrolled" array) instead of an array, as other parts of the code may already depend on operations performed on the array (e.g. using a `range` loop).

It is my opinion that marshaling/unmarshaling library should support unmodified user types as much as possible. The `csvutil` library already does a great job at this! Since it infers header names from field names, checks if standard (un)marshaling interfaces are implemented (e.g. `encoding.TextUnmarshaler`), and handles a variety of value formats (e.g. floating-point values, strings, integers, (even byte sequences) etc).

It is one of those things where you implement something once, and it provides benefits for all.

Using JSON, you can normally just encode/decode any arbitrary data type without modification, which is incredibly powerful. For inherent reasons, CSV cannot be made to support arbitrary nested data types, since the data is represented in a 2d sheet. That being said, the capabilities may be extended so support as much as possible (where it makes sense) to allow users to use data types unmodified (or with added tags) to marshal and unmarshal to and from CSV format.

I would fully understand if you prefer not to increase the complexity of the code base and think this is a very good sign that you care about the maintainability of `csvutil` and its code quality.

Let me know your thoughts :)

Cheers,
Robin

**Comment by jszwec** [comment]
I agree with your reasoning, but let's consider the following nested structures:

```go
type A struct {
	A string `csv:"a_"`
}

type B struct {
	As [2]A `csv:"inner_,inline"`
}

type C struct {
	Foo [2]B `csv:"foo_,inline"`
}
```

If Im not mistaken we would end up with the following header:
```
foo_inner_a_11
foo_inner_a_21
foo_inner_a_12
foo_inner_a_22
```

The result of the above is somehow bothering me, and I have a feeling that is very limiting. In such a case I would rather see something like this:
```
foo_inner_a_1_1
foo_inner_a_2_1
foo_inner_a_1_2
foo_inner_a_2_2
```
I think that it is impossible to achieve without the "pattern" feature that I mentioned earlier. Introducing both features would complicate the logic significantly and it's difficult to say if it's worth it.

**Comment by mewmew** [comment]
I have tried to give it some thought, and it may be as you put it, that it would be difficult to handle nested arrays in a good and consistent way. Still have to give it some more thought. Just wanted to reply back, so you know I haven't stopped thinking about the way to implement this.

Cheerful winter wishes from Sweden :)
Robin

**Comment by jszwec** [comment]
Hey @mewmew! I hope you are doing well!
Since neither of us has come up with anything since November, I decided that I am going to close this issue for now. 
Please feel free to reopen it if you have new ideas!

**Comment by mewmew** [comment]
> Hey @mewmew! I hope you are doing well!
> Since neither of us has come up with anything since November, I decided that I am going to close this issue for now.
> Please feel free to reopen it if you have new ideas!

Hej @jszwec!

Thanks, I'm doing well :) Hope you are too!

Yeah, we can let this issue rest for a bit and if either of us think of a good way to implement it we can re-open and resume discussions.

I still think `csvutil` is tremendously useful.

Have a good start of the year and happy coding!

Cheers,
Robin

**Comment by mewmew** [comment]
Hi Jacek,

Hope life is treating you well.

I keep using your csvutil library and find it tremendously useful.

Like before, the only missing feature I see is a way to support "inline" slices and arrays fields.

I think there should be a generic solution to this problem by flattening and unflattening the structure before encoding and decoding the CSV data.

To give an example, the [jsonconv](https://github.com/tuan78/jsonconv) project of @tuan78 is capable of flattening arbitrarily deeply nested JSON into a one-dimensional structure (per element) that could then be converted to CSV.

To give and example, consider the following JSON data (`foo.json`):

<details><summary>foo.json</summary>

```json
[
	{
		"Name": "Hydra's",
		"ItemPowers": [
			{
				"ItemPowerID": "Mana : NN",
				"Min": 81,
				"Max": 100
			}
		],
		"QualityLvl": 60,
		"AffixItemTypes": "staff",
		"AffixGroup": "affix group either",
		"DoubleChance": false,
		"IsPositive": true,
		"MinValue": 19100,
		"MaxValue": 30000,
		"ValueMult": 13
	},
	{
		"Name": "Fine",
		"ItemPowers": [
			{
				"ItemPowerID": "NN% damage",
				"Min": 36,
				"Max": 50
			},
			{
				"ItemPowerID": "chance to hit : NN%",
				"Min": 6,
				"Max": 10
			}
		],
		"QualityLvl": 6,
		"AffixItemTypes": "bow | staff | weapon",
		"AffixGroup": "affix group either",
		"DoubleChance": true,
		"IsPositive": true,
		"MinValue": 1100,
		"MaxValue": 1700,
		"ValueMult": 7
	},
	{
		"Name": "Crimson",
		"ItemPowers": [
			{
				"ItemPowerID": "Resist Fire : +NN%",
				"Min": 21,
				"Max": 30
			}
		],
		"QualityLvl": 10,
		"AffixItemTypes": "jewelry | bow | staff | weapon | shield | armor",
		"AffixGroup": "affix group either",
		"DoubleChance": false,
		"IsPositive": true,
		"MinValue": 2100,
		"MaxValue": 3000,
		"ValueMult": 2
	}
]
```

</details>

Running the command flattens the JSON data (which can be arbitrarily nested and may contain both slices and arrays as well as embedded structures:

```bash
# Install jsonconv tool
go install github.com/tuan78/jsonconv/cmd/jsonconv@latest

# Flatten JSON data.
jsonconv csv --fga "." -i foo.json > bar.csv
```

Contents of output `bar.csv`.

<details><summary>bar.json</summary>

```csv
AffixGroup,AffixItemTypes,DoubleChance,IsPositive,ItemPowers[0].ItemPowerID,ItemPowers[0].Max,ItemPowers[0].Min,ItemPowers[1].ItemPowerID,ItemPowers[1].Max,ItemPowers[1].Min,MaxValue,MinValue,Name,QualityLvl,ValueMult
affix group either,staff,false,true,Mana : NN,100,81,,,,30000,19100,Hydra's,60,13
affix group either,bow | staff | weapon,true,true,NN% damage,50,36,chance to hit : NN%,10,6,1700,1100,Fine,6,7
affix group either,jewelry | bow | staff | weapon | shield | armor,false,true,Resist Fire : +NN%,30,21,,,,3000,2100,Crimson,10,2
```

</details>

The CSV visualized using Gnumerics:
![gnumerics](https://github.com/user-attachments/assets/6aea40aa-be75-4871-b10a-a13282dba9a5)

Let me know what you think : )

It seems like a powerful approach to support arbitrarily nested data structures to be converted to CSV and back.

Happy winter wishes,
Robin
