### ISSUE TITLE
Decoding CSV with no header

### ISSUE THREAD

**Issue by gabriel-vasile** [jszwec/csvutil#47]
I'm not quite sure this is a bug or a mistake in my code.

Starting from the example of decoding CSV without header: https://play.golang.org/p/0FAo7BHFUt_M

I changed the "csv" tag to "json", expecting the decoding to still work, but it doesn't: https://play.golang.org/p/R1hLXkq12YF 

Edit: this is not json specific. Changing the tag to any string breaks decoding.

**Comment by jszwec** [comment]
You need to set Tag on the Decoder to json, otherwise it looks for csv: https://play.golang.org/p/x8IzzO48Ig3

**Comment by gabriel-vasile** [comment]
Thanks!
