### ISSUE TITLE
Handling non-string values

### ISSUE THREAD

**Issue by p3lim** [jszwec/csvutil#51]
Assuming I have the following struct I want to decode/encode:
```go
type Data struct {
    Addr net.HardwareAddr
}
```
`net.HardwareAddr` is a `[]byte`, and when encoded will output the `string(Addr)` version of the field instead of the output from `Addr.String()` as I would want. E.g. if `Addr` is `00:11:22:33:44:55` and I encode that I'd get `ABEiM0RV`, not the string representation of `net.HardwareAddr`.

Since `net.HardwareAddr` is a type I don't control I can't just add methods to it for custom marshaling, so I wanted to try out the `.Map` method on the decoder (to start with, still don't know how I'd handle this for encoding).

But I'm having trouble understanding how `.Map` is supposed to work, given this example:

```go
type Data struct {
	Addr net.HardwareAddr
}

r := `addr
00:11:22:33:44:55
11:22:33:44:55:66
22:33:44:55:66:77`

dec, err := csvutil.NewDecoder(csv.NewReader(strings.NewReader(r)))
if err != nil {
	panic(err)
}
dec.Map = func(field, column string, v interface{}) string {
	fmt.Println(field)
	fmt.Println(column)
	fmt.Println(v)
	return field
}

var dd []Data
for {
	var d Data
	if err := dec.Decode(&d); err == io.EOF {
		break
	} else if err != nil {
		panic(err)
	}
	dd = append(dd, d)
}

fmt.Println(dd) // [{} {} {}]
```

The `.Map` function is never called, I never see those prints, what am I doing wrong?

I'm using v1.6.0 on go1.17

**Comment by p3lim** [comment]
Issue was my header was lower case, didn't think it was case-sensitive (unlike other decoders).

I'm still curious as to how I would solve the type mapping though, in case you have a good suggestion for that.

**Comment by p3lim** [comment]
Figured it out, dec/enc.Register is pretty powerful:

```go
dec.Register(func(data []byte, f *net.HardwareAddr) error {
	addr, err := net.ParseMAC(string(data))
	if err != nil {
		return err
	}
	*f = addr
	return nil
})
```

**Comment by jszwec** [comment]
Yep, Register is your best bet in this case.

Yes, header is case sensitive because lowering it by default would be too dangerous. In some edge cases we could create conflicting headers. However, if you don't want it to be case sensitive you can always call this: https://pkg.go.dev/github.com/jszwec/csvutil#Decoder.NormalizeHeader
```go
dec.NormalizeHeader(strings.Lower)
```
