### ISSUE TITLE
How to read header structure inconsistency，Or start from the specified line?

### ISSUE THREAD

**Issue by htyypt** [jszwec/csvutil#55]
error: record on line 9: wrong number of fields

I can read normally by deleting the first 10 lines

How can I read all, or ignore the first 10 lines

![image](https://user-images.githubusercontent.com/81215528/189115025-e89fe5cf-9cdf-43bd-8e6e-0def97ba719c.png)

**Comment by jszwec** [comment]
There are many ways to do it. The easiest way is to use csv.Reader + for loop until you reach you desired line. However, csvutil will not do this for you
