### ISSUE TITLE
csvutil: unsupported type: []string

### ISSUE THREAD

**Issue by mr-od** [jszwec/csvutil#56]
I am trying to unmarshal this into a struct. 
`	ImgUrl      Strings        `csv:"img_url"`
	ImgName     Strings        `csv:"img_name"`
`
Using the Example for Marshalling, i still get the error. 

`
func (s Strings) MarshalCSV() ([]byte, error) {
	return []byte(strings.Join(s, ",")), nil // strings.Join takes []string but it will also accept Strings
}
`
I tried to write an unmarshaller.
`
func (s Strings) UnmarshalCSV(data string) error {
	split := strings.Split(string(data), ",")
	s = split
	return nil
}
`
But still getting the error.

**Comment by jszwec** [comment]
you didn't provide enough information for me to help you

> But still getting the error.

you didn't write what error you are getting either

However, from what I understand your problem lies in lack of pointer receiver 
`func (s Strings) UnmarshalCSV(` should be `func (s *Strings) UnmarshalCSV(`

https://go.dev/tour/methods/4

also look here for more examples: https://github.com/jszwec/csvutil#custom-types-and-overrides-

It's a bug in your code, not in csvutil - Closing

**Comment by mr-od** [comment]
I'm sorry for not tagging it as a question. It's not a bug I believe. I get the error unsupported type api.Strings. There is no example for unmarshalling a slice of strings. I only found an example for marshaling. If you would be kind enough to tell me what to do. Do I do a strings.split in order to unmarshall the []string? There is no example for unmarshalling []string.

**Comment by jszwec** [comment]
> There is no example for unmarshalling a slice of strings

because slice of strings as a column is not a usual use case. You did not provide what your data looks like so I cannot help you. I don't know what you are trying to achieve

**Comment by jszwec** [comment]
Example based on what you told me - https://go.dev/play/p/qFmk6ktCGd9

Like I mentioned before, you missed pointer receiver and did not follow the documentation - https://pkg.go.dev/github.com/jszwec/csvutil#Unmarshaler - UnmarshalCSV takes []byte, not string

**Comment by mr-od** [comment]
I fixed it. I used the pointer like you suggested. Thanks so much. You might want to include the unmarshalling of slice to the example.
`func (s *Strings) UnmarshalCSV(data []byte) error {
	ss := strings.Split(string(data), ",")
	*s = Strings(ss)

	return nil // strings.Join takes []string but it will also accept Strings
}`

**Comment by mr-od** [comment]
This is what i was trying to achieve. 
`    
"imgs_url": [
        "1166.jpg",
        "1188.jpg"
    ],
    "imgs_name": [
        "1166.jpg",
        "1188.jpg"
    ]
`
When a column contains a slice of strings.

**Comment by mr-od** [comment]
Thanks for the package. Very simple to understand and great documentation.
