### ISSUE TITLE
int in quotas

### ISSUE THREAD

**Issue by novikovsergey** [jszwec/csvutil#6]
Hi, I try to use your csvutil lib, It very useful, thanx, but I have a problem with some csv's files:

1. some my clients marshall csv with INT in quotes like 
"id";"et";"v";"dt"
"1000000089";"1";"XUSFSTDE4E0001040";"2016-01-29"
and when i try to unmarshall it, I have an error: `csvutil: cannot unmarshal  into Go value of type int`

2. some csv files have float with comma(,) as decimal delimeter like  10190,45
and I have errror: `csvutil: cannot unmarshal 10190,45 into Go value of type float64`

Can you explain how I should resolve this issues?
In README I see decoder.Map function maybe It that's what I need? But it not represent in release 1.1.1, which I got by go dep ensure automaticaly

**Comment by jszwec** [comment]
Hello,

1.  I wrote a small program using your data and I don't see any problems with it. Std csv.Reader removes the quotes while reading the record, so it should be fine.

```go
package main

import (
	"bytes"
	"encoding/csv"
	"fmt"
	"io"
	"log"

	"github.com/jszwec/csvutil"
)

type Foo struct {
	ID int `csv:"id"`
	ET int `csv:"et"`
}

func main() {
	data := []byte(`"id";"et";"v";"dt"
"1000000089";"1";"XUSFSTDE4E0001040";"2016-01-29"`)

	r := csv.NewReader(bytes.NewReader(data))
	r.Comma = ';'

	dec, err := csvutil.NewDecoder(r)
	if err != nil {
		log.Fatal(err)
	}

	for {
		var f Foo
		if err := dec.Decode(&f); err == io.EOF {
			break
		} else if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%+v\n", f)
	}
}
```

```bash
jszwec@jszwec: ~/src/github.com/jszwec/csvutil/cmd/issue6 ((d0aa9ba...))  $ go run main.go
{ID:1000000089 ET:1}
```

2. You are right, dec.Map would be the way to go, but you can also achieve this by implementing your own csvutil.Unmarshaler type.

dec.Map
```go
	dec.Map = func(field, column string, v interface{}) string {
		switch v.(type) {
		case float32, float64:
			return strings.Replace(field, ",", ".", 1)
		}
		return field
	}
```

Unmarshaler
```go
type Float float64

func (f *Float) UnmarshalCSV(data []byte) error {
	ff, err := strconv.ParseFloat(string(bytes.Replace(data, []byte(","), []byte("."), 1)), 64)
	if err != nil {
		return err
	}
	*f = Float(ff)
	return nil
}
```

I am planning to release v1.2.0 (hopefully) sometime next week.

**Comment by novikovsergey** [comment]
Thank you very much!
