### ISSUE TITLE
Read file without defining a struct beforehand, such as into  a `[]map[string]string`?

### ISSUE THREAD

**Issue by FrankDMartinez** [jszwec/csvutil#60]
Hi.

I hope you are having a great new year so far.

If I wanted to read a CSV file into a `[]map[string]string` using this library, how would I do so?

Thanks in advance.

**Comment by jszwec** [comment]
This is not supported. This package encodes/decodes only struct values and I have no plans on adding maps support.

However, check "Unmarshal and metadata" section in README. You can turn it into a helper function that will give you what you need
