### ISSUE TITLE
Add support writing the header if a slice is empty

### ISSUE THREAD

**Issue by cia-rana** [jszwec/csvutil#69]
If slice is empty, the header is not output. Are there plans to support outputting it?

Sample code:
```go
func main() {
	users := []struct {
		Name string
		Age  int
	}{}

	var buf bytes.Buffer
	w := csv.NewWriter(&buf)
	csvutil.NewEncoder(w).Encode(users)
	w.Flush()

	fmt.Println(buf.String())
}
```

Want:
```
Name,Age
```

Actual:
```

```

**Comment by jszwec** [comment]
Please read the documentation before creating an issue: https://pkg.go.dev/github.com/jszwec/csvutil#Encoder.EncodeHeader

https://go.dev/play/p/y7X3sHYMW-S

**Comment by iwamura-koya-ab** [comment]
@jszwec 
Thanks for the reply!
Your example works well if the type is known. However, if the type is hidden by `interface`, additional implementation is required, such as extracting the type information with reflect package. Therefore, I hope this library can solve this problem.

**Comment by jszwec** [comment]
Are you suggesting that `EncodeHeader` could understand slice argument and do it for you?
That's not a crazy idea, and not very hard to implement.

example:
```go
var v any = []Users{}
enc.EncodeHeader(v) // that would determine the `User` type
```

**Comment by cia-rana** [comment]
> Are you suggesting that `EncodeHeader` could understand slice argument and do it for you? That's not a crazy idea, and not very hard to implement.
> 
> example:
> 
> ```go
> var v any = []Users{}
> enc.EncodeHeader(v) // that would determine the `User` type
> ```

That would be ideal for me, but if it goes against the policy of this library, then it doesn't have to.

**Comment by jszwec** [comment]
That's fine with me. It's reasonable. Feel free to implement it if I dont get to it first
